#!/usr/bin/env python3
"""Regenerate README.md (bilingual EN/RU faceted catalog) from project frontmatter.

Usage:
  python3 scripts/gen_catalog.py            # write README.md
  python3 scripts/gen_catalog.py --check    # exit 1 if README.md would change (CI staleness gate)
"""
import re, sys
from _common import (load_projects, ROOT, STATUS_RU, TIER_RU, DOMAIN_RU,
                     TRACK_ORDER, TRACK_LABEL, TRACK_LABEL_RU, TRACK_DESC)

BANNER = "<!-- GENERATED by scripts/gen_catalog.py — DO NOT EDIT. Run the script to refresh. -->\n\n"

HEADER = """# ASRP — Engineering Portfolio / Инженерное портфолио

<div align="center">

[![ASRP](https://img.shields.io/badge/ASRP-Engineering-blue)](https://asrp.tech)
![Language](https://img.shields.io/badge/Language-EN%2FRU-brightgreen)

**Part of the ASRP ecosystem / Часть экосистемы ASRP**

</div>

**EN:** **ASRP** designs and builds production software: conversational voice-AI, real-time
communications, agent infrastructure, and backend platforms. Each entry below is a project ASRP
delivered — some anonymized (client under NDA), some shown in full with live links.

**RU:** **ASRP** проектирует и создаёт продакшн-софт: диалоговый голосовой ИИ, real-time-коммуникации,
инфраструктуру агентов и бэкенд-платформы. Каждая запись ниже — проект, реализованный ASRP: часть
анонимизирована (клиент под NDA), часть показана полностью, с рабочими ссылками.

To discuss a project or request deeper detail under NDA / Обсудить проект или запросить детали под NDA: **info@asrp.tech**
"""

TYPE_LABEL = {"own-product": "Own products & shipped platforms",
              "client-engagement": "Client engagements (anonymized)"}
TYPE_LABEL_RU = {"own-product": "Собственные продукты и запущенные платформы",
                  "client-engagement": "Клиентские проекты (анонимизированные)"}
TYPE_ORDER = ["own-product", "client-engagement"]


def anchor(en, ru):
    """Mirror GitHub's heading-id algorithm for an 'EN / RU' heading."""
    slug = re.sub(r"[^\w\s-]", "", f"{en} / {ru}".lower(), flags=re.UNICODE)
    return slug.replace(" ", "-")


def heading(level, en, ru):
    return f"{'#' * level} {en} / {ru}"


def period(m):
    p = m.get("period") or {}
    s, e = p.get("start"), p.get("end")
    return f"{s or '?'} – {e or 'ongoing'}"


def period_ru(m):
    p = m.get("period") or {}
    s, e = p.get("start"), p.get("end")
    return f"{s or '?'} – {e or 'наст. время'}"


def links_md(m):
    l = m.get("links") or {}
    parts = [f"[{k}]({l[k]})" for k in ("repo", "demo", "site", "docs") if (l.get(k) or "").strip()]
    return " · ".join(parts)


def ru_or_pending(m, key):
    v = (m.get(key) or "").strip()
    return v if v else "_перевод в работе / translation pending_"


def highlights_ru_or_pending(m):
    hl_ru = m.get("highlights_ru") or []
    if hl_ru:
        return hl_ru
    return ["_перевод в работе / translation pending_"]


def render(projects):
    out = [BANNER, HEADER]

    featured = [p for p in projects if (p["meta"].get("featured") or 0) >= 1]
    tech = sorted({s for p in projects for s in (p["meta"].get("stack") or [])})

    # --- Quick Navigation --------------------------------------------------
    nav_sections = []
    if featured:
        nav_sections.append(("Featured", "Избранное",
                              "Headline projects across both engagement types",
                              "Ключевые проекты обоих типов"))
    for tr in TRACK_ORDER:
        if any(p["meta"].get("track") == tr for p in projects):
            den, dru = TRACK_DESC[tr]
            nav_sections.append((TRACK_LABEL[tr], TRACK_LABEL_RU[tr], den, dru))
    if tech:
        nav_sections.append(("Technology", "Технологии",
                              "Stack used across the portfolio", "Стек, используемый в портфолио"))
    nav_sections.append(("Confidentiality", "Конфиденциальность",
                          "How disclosure tiers work", "Как устроены уровни раскрытия"))
    nav_sections.append(("Index", "Индекс",
                          "Full sortable table of every project", "Полная таблица всех проектов"))
    nav_sections.append(("Contact", "Контакты", "How to reach ASRP", "Как связаться с ASRP"))

    out.append(f"\n## Quick Navigation / Быстрая навигация\n")
    out.append("| Section / Раздел | Description / Описание |\n| --- | --- |")
    for en, ru, den, dru in nav_sections:
        out.append(f"| [{en} / {ru}](#{anchor(en, ru)}) | {den} / {dru} |")
    out.append("")

    # --- Featured ------------------------------------------------------------
    if featured:
        out.append(f"\n{heading(2, 'Featured', 'Избранное')}\n")
        out.append("| Project / Проект | What it is / Что это | Status / Статус |\n| --- | --- | --- |")
        for p in featured:
            m = p["meta"]
            status_ru = STATUS_RU.get(m["status"], m["status"])
            out.append(f"| **[{m['title']} / {ru_or_pending(m, 'title_ru')}](projects/{p['slug']}/)** | "
                        f"{m['summary']}<br>{ru_or_pending(m, 'summary_ru')} | {m['status']} / {status_ru} |")
        out.append("")

    # --- Projects grouped by track (Telephony / AI-organization) -------------
    for tr in TRACK_ORDER:
        group = [p for p in projects if p["meta"].get("track") == tr]
        if not group:
            continue
        out.append(f"\n{heading(2, TRACK_LABEL[tr], TRACK_LABEL_RU[tr])}\n")
        for p in group:
            m = p["meta"]
            status_ru = STATUS_RU.get(m["status"], m["status"])
            title_ru = ru_or_pending(m, "title_ru")
            out.append(f"### [{m['title']}](projects/{p['slug']}/) / [{title_ru}](projects/{p['slug']}/)")
            lm = links_md(m)
            meta_en = f"*{m.get('role', '')} · {period(m)} · {m['status']}*"
            meta_ru = f"*{ru_or_pending(m, 'role_ru')} · {period_ru(m)} · {status_ru}*"
            if lm:
                meta_en += f" · {lm}"
                meta_ru += f" · {lm}"
            out.append(meta_en)
            out.append(meta_ru + "\n")
            out.append(f"**EN:** {m['summary']}\n")
            out.append(f"**RU:** {ru_or_pending(m, 'summary_ru')}\n")
            out.append("**Highlights:**")
            for h in (m.get("highlights") or []):
                out.append(f"- {h}")
            out.append("\n**Особенности:**")
            for h in highlights_ru_or_pending(m):
                out.append(f"- {h}")
            out.append("")

    # --- Technology ------------------------------------------------------------
    if tech:
        out.append(f"\n{heading(2, 'Technology', 'Технологии')}\n")
        out.append(" · ".join(f"`{t}`" for t in tech) + "\n")

    # --- Confidentiality ---------------------------------------------------
    out.append(f"\n{heading(2, 'Confidentiality', 'Конфиденциальность')}\n")
    out.append(
        "**EN:** Every case study is published at one of two visible disclosure tiers. **Public** — the "
        "client or product is named, with live links where available. **Anonymized** — the client is never "
        "named and no links are shown; identifying detail is generalized into a safe one-line setting. A "
        "third tier, **nda-only**, exists only in ASRP's private working repo, for material excluded from "
        "any public export. See the Disclosure column in [Index / Индекс](#index--индекс) for this "
        "repository's actual mix.\n")
    out.append(
        "**RU:** Каждый кейс публикуется на одном из двух видимых уровней раскрытия. **Public "
        "(публичный)** — клиент или продукт назван, при наличии — с рабочими ссылками. **Anonymized "
        "(анонимизированный)** — клиент никогда не называется, ссылки не публикуются; идентифицирующие "
        "детали обобщены в безопасную обзорную строку. Третий уровень, **nda-only**, существует только в "
        "приватном рабочем репозитории ASRP — для материалов, исключённых из любого публичного экспорта. "
        "Фактическое соотношение уровней для этого репозитория — в колонке Disclosure таблицы "
        "[Index / Индекс](#index--индекс).\n")

    # --- Index ---------------------------------------------------------------
    n_pub = sum(1 for p in projects if p["meta"].get("confidentiality") == "public")
    n_anon = sum(1 for p in projects if p["meta"].get("confidentiality") == "anonymized")
    out.append(f"\n{heading(2, 'Index', 'Индекс')}\n")
    out.append("| Project / Проект | Type / Тип | Domain / Домен | Period / Период | "
                "Status / Статус | Disclosure / Раскрытие |\n| --- | --- | --- | --- | --- | --- |")
    for p in sorted(projects, key=lambda x: x["slug"]):
        m = p["meta"]
        domains = m.get("domain") or []
        domains_ru = ", ".join(DOMAIN_RU.get(d, d) for d in domains)
        conf = m["confidentiality"]
        out.append(f"| [{p['slug']}](projects/{p['slug']}/) | {m['type']} | "
                    f"{', '.join(domains)}<br>{domains_ru} | {period(m)} | "
                    f"{m['status']}<br>{STATUS_RU.get(m['status'], m['status'])} | "
                    f"{conf}<br>{TIER_RU.get(conf, conf)} |")
    out.append(f"\n*{len(projects)} projects · {n_pub} named/attributed · {n_anon} anonymized "
               "(client under NDA). Deeper detail and full case studies shared on request.*\n"
               f"*{len(projects)} проектов · {n_pub} названы/атрибутированы · {n_anon} анонимизированы "
               "(клиент под NDA). Более глубокие детали и полные кейсы — по запросу.*\n")

    # --- Contact ---------------------------------------------------------------
    out.append(f"\n{heading(2, 'Contact', 'Контакты')}\n")
    out.append("| Field / Поле | Value / Значение |\n| --- | --- |")
    out.append("| **Organization / Организация** | Advanced Scientific Research Projects LLP "
                "(ТОО «Перспективные Научно-Исследовательские Разработки») |")
    out.append("| **Country / Страна** | Republic of Kazakhstan / Республика Казахстан |")
    out.append("| **Website / Веб-сайт** | [asrp.tech](https://asrp.tech) |")
    out.append("| **Email** | info@asrp.tech |")
    out.append("\n---\n")
    out.append("**Part of the ASRP ecosystem / Часть экосистемы ASRP** — see "
                "[asrp.tech](https://asrp.tech) for the full portfolio of ASRP ventures / "
                "полный портфель проектов ASRP.\n")
    return "\n".join(out)


def main():
    projects = load_projects()
    content = render(projects)
    readme = ROOT / "README.md"
    if "--check" in sys.argv:
        current = readme.read_text() if readme.exists() else ""
        if current.strip() != content.strip():
            print("README.md is STALE — run: python3 scripts/gen_catalog.py")
            return 1
        print("README.md up to date")
        return 0
    readme.write_text(content)
    print(f"wrote README.md ({len(projects)} projects)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
